-- MySQL Script generated by MySQL Workbench
-- Tue Mar 30 01:07:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Brand` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Brand` (
  `BrandID` INT NOT NULL,
  `Brand_Name` VARCHAR(45) NULL,
  `Year_of_Creation` VARCHAR(45) NULL,
  `Car_CarID` INT NOT NULL,
  PRIMARY KEY (`BrandID`),
  CONSTRAINT `fk_Brand_Car1`
    FOREIGN KEY (`Car_CarID`)
    REFERENCES `Car` (`CarID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Car` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Car` (
  `CarID` INT NOT NULL,
  `Car_Name` VARCHAR(45) NULL,
  `Brand_Name` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `Seat_NB` INT NULL,
  `Price` INT NULL,
  PRIMARY KEY (`CarID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CarID_UNIQUE` ON `Car` (`CarID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Costumer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Costumer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Costumer` (
  `CostumerID` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Dealer_Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone_NB` INT NULL,
  `OwnerShip_OwnerShipID` INT NOT NULL,
  `Car_CarID` INT NOT NULL,
  PRIMARY KEY (`CostumerID`),
  CONSTRAINT `fk_Costumer_OwnerShip`
    FOREIGN KEY (`OwnerShip_OwnerShipID`)
    REFERENCES `OwnerShip` (`OwnerShipID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costumer_Car1`
    FOREIGN KEY (`Car_CarID`)
    REFERENCES `Car` (`CarID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CostumerID_UNIQUE` ON `Costumer` (`CostumerID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `OwnerShip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OwnerShip` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `OwnerShip` (
  `OwnerShipID` INT NOT NULL,
  `Date` DATE NULL,
  `Time` TIME NULL,
  `Dealer_Name` VARCHAR(45) NULL,
  `Car_CarID` INT NOT NULL,
  `Brand_BrandID` INT NOT NULL,
  PRIMARY KEY (`OwnerShipID`),
  CONSTRAINT `fk_OwnerShip_Car1`
    FOREIGN KEY (`Car_CarID`)
    REFERENCES `Car` (`CarID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OwnerShip_Brand1`
    FOREIGN KEY (`Brand_BrandID`)
    REFERENCES `Brand` (`BrandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
